s@  \<a href="http://maven.apache.org/" title="Built by Maven" id="poweredBy"\>@<a href="http://sourceforge.net"><img src="http://sflogo.sourceforge.net/sflogo.php?group_id=170262&amp;type=2" width="125" height="37" border="0" alt="SourceForge.net Logo" /></a>@ig;
s@              \<img alt="Built by Maven" src="\./images/logos/maven-feather.png"\>\</img\>@<p>@ig;
s@\</body\>@\<script src\=\"http\:\/\/www.google-analytics.com\/urchin.js\" type\=\"text\/javascript\"\>\<\/script\>\<script type\=\"text\/javascript\"\>_uacct \= \"UA-697468-1\";urchinTracker\(\);\<\/script\>\<\/body\>@ig;
s@href="https://sourceforge.net/project/showfiles.php\?group_id\=170262"@href="https://sourceforge.net/project/showfiles.php\?group_id\=170262" target\="_new"@ig;
s@href="http://site.voila.fr/ressources-apple2/adtpro/adtpro.html"@href="http://site.voila.fr/ressources-apple2/adtpro/adtpro.html" target\="_new"@ig;
s@href="http://hanazam.net/apple/ageofii.htm"@href="http://hanazam.net/apple/ageofii.htm" target\="_new"@ig;
s@href="http://a2retrosystems.com/"@href="http://a2retrosystems.com/" target\="_new"@ig;
s@href="http://adt.berlios.de"@href="http://adt.berlios.de" target\="_new"@ig;
s@href="http://www.connectworld.net/cgi-bin/iec/05MCAOSerial.html"@href="http://www.connectworld.net/cgi-bin/iec/05MCAOSerial.html" target\="_new"@ig;
s@webringreplaced@<script type="text/javascript"src="http://ss.webring.com/navbar?f=j;y=schmidtd;u=adtpro"></script>Powered by <a href="http://dir.webring.com/rw" target=_top>WebRing</a>.@ig;
s@&amp;#223;@&#223;@ig;
