s@v\.r\.m@2.0.2@ig;
s@\<a href="http://maven.apache.org/" title="Built by Maven" class="poweredBy"\>@<a href="https://github.com/ADTPro/adtpro"><img src="https://assets-cdn.github.com/images/modules/logos_page/GitHub-Logo.png" /></a>@ig;
s@\<img class="builtBy" alt="Built by Maven" src="\./images/logos/maven-feather.png" \/\>@@ig;
s@\</body\>@\<script src\=\"http\:\/\/www.google-analytics.com\/urchin.js\" type\=\"text\/javascript\"\>\<\/script\>\<script type\=\"text\/javascript\"\>_uacct \= \"UA-697468-1\";urchinTracker\(\);\<\/script\>\<\/body\>@ig;
s@(href="http://www.youtube.com/watch\?v=CMF3PL17kqg)(.*)"@\1\2" target\="_new"@ig;
s@href="http://dataswamp.net/apple2eserialterm/index.php"@href="http://dataswamp.net/apple2eserialterm/index.php" target\="_new"@ig;
s@href="http://ressources-apple2.voila.net/adtpro/adtpro.html"@href="http://ressources-apple2.voila.net/adtpro/adtpro.html" target\="_new"@ig;
s@href="http://boutillon.free.fr/Underground/Outils/ADTPro_iMac/ADTPro_iMac.html"@href="http://boutillon.free.fr/Underground/Outils/ADTPro_iMac/ADTPro_iMac.html" target\="_new"@ig;
s@href="http://hanazam.net/apple/ageofii.htm"@href="http://hanazam.net/apple/ageofii.htm" target\="_new"@ig;
s@href="http://a2retrosystems.com/"@href="http://a2retrosystems.com/" target\="_new"@ig;
s@href="http://www.wbwip.com/shh/"@href="http://www.wbwip.com/shh/" target\="_new"@ig;
s@href="http://adt.berlios.de"@href="http://adt.berlios.de" target\="_new"@ig;
s@href="https://juiced.gs"@href="https://juiced.gs" target\="_new"@ig;
s@(href\=\"http://apple3.org)(.*)\"@\1\2" target\="_new"@ig;
s@(href\=\"http://retrofloppy.com)(.*)\"@\1\2" target\="_new"@ig;
s@href="http://www.connectworld.net/cgi-bin/iec/05MCAOSerial.html"@href="http://www.connectworld.net/cgi-bin/iec/05MCAOSerial.html" target\="_new"@ig;
s@href="http://seb.riot.org/appleII/aladt.sml"@href="http://seb.riot.org/appleII/aladt.sml" target\="_new"@ig;
s@href="http://dreher.net/?s=projects/CFforAppleII&amp;c=projects/CFforAppleII/main.php"@href="http://dreher.net/?s=projects/CFforAppleII&amp;c=projects/CFforAppleII/main.php" target\="_new"@ig;
s@href="http://www.callapple.org/uncategorized/announcing-prodos-2-4-for-all-apple-ii-computers/"@href="http://www.callapple.org/uncategorized/announcing-prodos-2-4-for-all-apple-ii-computers/" target\="_new"@ig;
s@href="http://oliverschmidt.github.io/ip65/"@href="http://oliverschmidt.github.io/ip65/" target\="_new"@ig;
s@href="hhttps://github.com/a2retrosystems/uthernet2/wiki/W5100-Shared-Access"@href="https://github.com/a2retrosystems/uthernet2/wiki/W5100-Shared-Access" target\="_new"@ig;
s@webringreplaced@<script type="text/javascript"src="http://ss.webring.com/navbar?f=j;y=schmidtd;u=adtpro"></script>Powered by <a href="http://dir.webring.com/rw" target=_top>WebRing</a>.@ig;
s@&amp;#223;@&#223;@ig;
